---
title: "Instructors' Area"
headless: no
weight: 40
widget: blank
subtitle: ''
hero_media: ctbf-welcome.jpg
design:
  columns: '2'
advanced:
  css_style: null
  css_class: null
---

# Interns (KIN494)

You will need to complete three (3) forms to enroll in the CTBF KIN 494 Internship.

## Form 1: Application Form

Time to complete: 20min


nomnoml::nomnoml ("[Signer]-[Supervisor]-[Faculty Lead]")


[<start>st]->[<state>plunder]
[plunder]->[<choice>more loot]
[more loot]->[st]
[more loot] no ->[<end>e]


{{% callout warning %}}

{{% /callout %}}

## Step 2: Internship Application

Download :
Application - https://canvas.csun.edu/courses/37918/files/9391375/download?wrap=1
Liability Waiver - https://canvas.csun.edu/courses/37918/files/9391185/download?wrap=1
Orientation Guidelines - https://canvas.csun.edu/courses/37918/files/9391186/download?wrap=1





{{< cta cta_text="Click here to register" cta_link="http://bit.ly/ctbf-register" cta_new_tab="true" >}}


{{% callout note %}}
When completing the Participant Data Form, you will be asked to complete and sign both the **CSUN Waiver of Liability and Hold Harmless Agreement** and the **Visual/Audio Image Release Form (optional)**.
{{% /callout %}}

{{% callout warning %}}
When completing the Participant Data Form, you will be asked about your medical history. If after answering the questions, it is indicated that a medical **clearance is recommended**, you will need approval from a health care professional before participating in the CTBF Program. Please, [contact us](#contact) if you have any questions.  
{{% /callout %}}

## Required Paperwork

Each semester, participants must complete the following required paperwork prior to participation: 

- Participant Data Form (completed online - refer to the link above)
- CSUN Waiver of Liability and Hold Harmless Agreement [^1]   
- Visual/Audio Image Release Form (optional) [^1]

For any questions or more information, please [contact us](#contact).

[^1]: Completed concomitantly with the Participant Data Form.